
{
    "components":[
        {
            "name":"unnamed",
            "type":"Rectangle",
            "x":84.0,
            "y":194.0,
            "outline_thickness":3.0,
            "outline_radius":0.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#ffffffff",
            "stop1":"#ffffffff",
            "width":600.0,
            "height":300.0
        },
        {
            "name":"unnamed",
            "type":"Rectangle",
            "x":653.0,
            "y":226.0,
            "outline_thickness":3.0,
            "outline_radius":0.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#ffffffff",
            "stop1":"#ffffffff",
            "width":600.0,
            "height":300.0
        },
        {
            "name":"unnamed",
            "type":"Rectangle",
            "x":500.0,
            "y":500.0,
            "outline_thickness":3.0,
            "outline_radius":0.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#ffffffff",
            "stop1":"#ffffffff",
            "width":600.0,
            "height":300.0
        }
    ]
}