
{
    "components":[
        {
            "name":"unnamed",
            "type":"Circle",
            "x":571.0,
            "y":475.0,
            "outline_thickness":3.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#FFFFFF",
            "stop1":"#FFFFFF",
            "radius":360.0
        },
        {
            "name":"unnamed",
            "type":"Rectangle",
            "x":280.0,
            "y":156.0,
            "outline_thickness":3.0,
            "outline_radius":0.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#ffffffff",
            "stop1":"#ffffffff",
            "width":600.0,
            "height":300.0
        },
        {
            "name":"unnamed",
            "type":"Rectangle",
            "x":295.0,
            "y":475.0,
            "outline_thickness":3.0,
            "outline_radius":0.0,
            "outline_color":"#000000",
            "focus_angle":0.0,
            "focus_distance":0.0,
            "center_X":0.0,
            "center_Y":0.0,
            "gradient_radius":0.0,
            "cyclemethod":"NO_CYCLE",
            "stop0":"#ffffffff",
            "stop1":"#ffffffff",
            "width":600.0,
            "height":300.0
        }
    ]
}